### ISSUE TITLE
Tutorial: Building A Dengue Visualisation Dashboard - problem with buildout git clone & other small fixes to complete tutorial

### ISSUE THREAD

**Issue by hexdump42** [koslab/pysiphae#1]
When running the tutorial I had a problem when running the bash -e build.sh step. It failed due the git command in the buildout.cfg needing an access token.

`pysiphae = git git@github.com:koslab/pysiphae.git`

I changed the line to

`pysiphae = git https://github.com/koslab/pysiphae.git`

and it worked..

**Comment by hexdump42** [comment]
When running the code changes for "Transforming Data And Publish as JSON" section the following error displayed when serve started

```
    __import__(modname)
  File "/Users/mark/swdev/pysiphae/venv/example.dengueviz/src/example/dengueviz/epiweek.py", line 126
    assert epiweek.calculate(date(*d)) == o
         ^
IndentationError: expected an indented block
```

Fixed by indenting the assert statement on line 126 of epiweek.py

**Comment by hexdump42** [comment]
I suggest that you add the path to the default.js file `src/example/dengueviz/static/default.js` in the tutorial text.

Once I had resolved these 3 small issues I was able to see a dashboard rendering the dengue data.

**Comment by kagesenshi** [comment]
fixed in latest push ..

thanks!!
